### ISSUE TITLE
Handle abort without throwing errors

### ISSUE THREAD

**Issue by mingard** [dadi/cli#16]
## Expected behaviour
When a user exits a process by means of selecting an option, a _goodbye_ message of some sort should be logged.

## Current behaviour
An Error is thrown e.g.
```shell
Error
    at inquirer.prompt.then.answers (/usr/local/lib/node_modules/@dadi/cli/lib/fs.js:39:25)
```

## Steps to reproduce
1. Type `dadi api new`
2. When prompted `The target directory (/home/ubuntu) is not empty. Would you like to proceed?` type 'n' to abort.
3. Observe error.

Further to this, I was unsure how to change the target directory. When I typed `dadi help api new` I was given only two options; name and version. If this is not possible I'll raise a separate ticket.

**Comment by eduardoboucas** [comment]
Are you running the latest version? The error you mentioned should've been fixed in 849e359220a8f2d302e1912787efa7db369e8547.

As for changing the target directory, the info in the help command isn't very clear. `name` should be `target-directory`, and it should explain that when that parameter is omitted the current working directory will be used. I'll work on that.

Would you mind creating a separate ticket for it, just so we can keep track?

**Comment by mingard** [comment]
Yes it appears I was on a 1.x release. I'll close this and raise a ticket for the `name` command.

**Comment by eduardoboucas** [comment]
Thanks dude! 👊
